services:
  web:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html
      - ./.development/configs/web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      HOSTNAME: web.${DOMAIN}
